#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GE19112017")]
	public partial class ReportSourceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ReportSourceDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GE19112017ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReportSourceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportSourceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportSourceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportSourceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Report_CashBankBook> tbl_Report_CashBankBooks
		{
			get
			{
				return this.GetTable<tbl_Report_CashBankBook>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Report_CashBankBooks")]
	public partial class tbl_Report_CashBankBook
	{
		
		private System.Nullable<long> _SrlNo;
		
		private System.Nullable<long> _SLNO;
		
		private System.Nullable<long> _CASHBANKID;
		
		private string _CASHBANKNAME;
		
		private System.Nullable<long> _ACCOUNT_GROUP;
		
		private string _GROUP_NAME;
		
		private string _SUBGRP_NAME;
		
		private string _BRANCHID;
		
		private string _BRANCH_DESC;
		
		private string _CustomerVendor;
		
		private string _Particulars;
		
		private string _HEADER_NARRATION;
		
		private string _SUBLEDGER;
		
		private System.Nullable<long> _DOC_ID;
		
		private string _DOCUMENT_NO;
		
		private string _TRAN_DATE;
		
		private string _MAINACCOUNT;
		
		private string _TRAN_TYPE;
		
		private string _MODULE_TYPE;
		
		private string _INSTRUMENT_NO;
		
		private string _INSTRUMENT_DATE;
		
		private string _DRAWEE_BANK;
		
		private System.Nullable<decimal> _DEBIT;
		
		private System.Nullable<decimal> _CREDIT;
		
		private System.Nullable<decimal> _Closing_Balance;
		
		private string _Closebal_DBCR;
		
		private System.Nullable<System.DateTime> _TRANDATE;
		
		public tbl_Report_CashBankBook()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrlNo", DbType="BigInt")]
		public System.Nullable<long> SrlNo
		{
			get
			{
				return this._SrlNo;
			}
			set
			{
				if ((this._SrlNo != value))
				{
					this._SrlNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLNO", DbType="BigInt")]
		public System.Nullable<long> SLNO
		{
			get
			{
				return this._SLNO;
			}
			set
			{
				if ((this._SLNO != value))
				{
					this._SLNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHBANKID", DbType="BigInt")]
		public System.Nullable<long> CASHBANKID
		{
			get
			{
				return this._CASHBANKID;
			}
			set
			{
				if ((this._CASHBANKID != value))
				{
					this._CASHBANKID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHBANKNAME", DbType="NVarChar(MAX)")]
		public string CASHBANKNAME
		{
			get
			{
				return this._CASHBANKNAME;
			}
			set
			{
				if ((this._CASHBANKNAME != value))
				{
					this._CASHBANKNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_GROUP", DbType="BigInt")]
		public System.Nullable<long> ACCOUNT_GROUP
		{
			get
			{
				return this._ACCOUNT_GROUP;
			}
			set
			{
				if ((this._ACCOUNT_GROUP != value))
				{
					this._ACCOUNT_GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_NAME", DbType="NVarChar(250)")]
		public string GROUP_NAME
		{
			get
			{
				return this._GROUP_NAME;
			}
			set
			{
				if ((this._GROUP_NAME != value))
				{
					this._GROUP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBGRP_NAME", DbType="NVarChar(300)")]
		public string SUBGRP_NAME
		{
			get
			{
				return this._SUBGRP_NAME;
			}
			set
			{
				if ((this._SUBGRP_NAME != value))
				{
					this._SUBGRP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHID", DbType="NVarChar(100)")]
		public string BRANCHID
		{
			get
			{
				return this._BRANCHID;
			}
			set
			{
				if ((this._BRANCHID != value))
				{
					this._BRANCHID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_DESC", DbType="NVarChar(300)")]
		public string BRANCH_DESC
		{
			get
			{
				return this._BRANCH_DESC;
			}
			set
			{
				if ((this._BRANCH_DESC != value))
				{
					this._BRANCH_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerVendor", DbType="NVarChar(MAX)")]
		public string CustomerVendor
		{
			get
			{
				return this._CustomerVendor;
			}
			set
			{
				if ((this._CustomerVendor != value))
				{
					this._CustomerVendor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Particulars", DbType="NVarChar(MAX)")]
		public string Particulars
		{
			get
			{
				return this._Particulars;
			}
			set
			{
				if ((this._Particulars != value))
				{
					this._Particulars = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEADER_NARRATION", DbType="NVarChar(MAX)")]
		public string HEADER_NARRATION
		{
			get
			{
				return this._HEADER_NARRATION;
			}
			set
			{
				if ((this._HEADER_NARRATION != value))
				{
					this._HEADER_NARRATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBLEDGER", DbType="NVarChar(MAX)")]
		public string SUBLEDGER
		{
			get
			{
				return this._SUBLEDGER;
			}
			set
			{
				if ((this._SUBLEDGER != value))
				{
					this._SUBLEDGER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_ID", DbType="BigInt")]
		public System.Nullable<long> DOC_ID
		{
			get
			{
				return this._DOC_ID;
			}
			set
			{
				if ((this._DOC_ID != value))
				{
					this._DOC_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENT_NO", DbType="NVarChar(300)")]
		public string DOCUMENT_NO
		{
			get
			{
				return this._DOCUMENT_NO;
			}
			set
			{
				if ((this._DOCUMENT_NO != value))
				{
					this._DOCUMENT_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAN_DATE", DbType="NVarChar(10)")]
		public string TRAN_DATE
		{
			get
			{
				return this._TRAN_DATE;
			}
			set
			{
				if ((this._TRAN_DATE != value))
				{
					this._TRAN_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAINACCOUNT", DbType="NVarChar(300)")]
		public string MAINACCOUNT
		{
			get
			{
				return this._MAINACCOUNT;
			}
			set
			{
				if ((this._MAINACCOUNT != value))
				{
					this._MAINACCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAN_TYPE", DbType="NVarChar(300)")]
		public string TRAN_TYPE
		{
			get
			{
				return this._TRAN_TYPE;
			}
			set
			{
				if ((this._TRAN_TYPE != value))
				{
					this._TRAN_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_TYPE", DbType="NVarChar(300)")]
		public string MODULE_TYPE
		{
			get
			{
				return this._MODULE_TYPE;
			}
			set
			{
				if ((this._MODULE_TYPE != value))
				{
					this._MODULE_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSTRUMENT_NO", DbType="NVarChar(35) NOT NULL", CanBeNull=false)]
		public string INSTRUMENT_NO
		{
			get
			{
				return this._INSTRUMENT_NO;
			}
			set
			{
				if ((this._INSTRUMENT_NO != value))
				{
					this._INSTRUMENT_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSTRUMENT_DATE", DbType="NVarChar(10)")]
		public string INSTRUMENT_DATE
		{
			get
			{
				return this._INSTRUMENT_DATE;
			}
			set
			{
				if ((this._INSTRUMENT_DATE != value))
				{
					this._INSTRUMENT_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWEE_BANK", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string DRAWEE_BANK
		{
			get
			{
				return this._DRAWEE_BANK;
			}
			set
			{
				if ((this._DRAWEE_BANK != value))
				{
					this._DRAWEE_BANK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEBIT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> DEBIT
		{
			get
			{
				return this._DEBIT;
			}
			set
			{
				if ((this._DEBIT != value))
				{
					this._DEBIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDIT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CREDIT
		{
			get
			{
				return this._CREDIT;
			}
			set
			{
				if ((this._CREDIT != value))
				{
					this._CREDIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Closing_Balance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Closing_Balance
		{
			get
			{
				return this._Closing_Balance;
			}
			set
			{
				if ((this._Closing_Balance != value))
				{
					this._Closing_Balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Closebal_DBCR", DbType="NVarChar(2)")]
		public string Closebal_DBCR
		{
			get
			{
				return this._Closebal_DBCR;
			}
			set
			{
				if ((this._Closebal_DBCR != value))
				{
					this._Closebal_DBCR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> TRANDATE
		{
			get
			{
				return this._TRANDATE;
			}
			set
			{
				if ((this._TRANDATE != value))
				{
					this._TRANDATE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
